-- 1. Create PROFILES table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  master BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Create DEVOTEES table
CREATE TABLE devotees (
  id TEXT PRIMARY KEY, -- We use custom IDs like DEV-1001
  name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  total_expected DECIMAL(12,2) DEFAULT 0,
  total_paid DECIMAL(12,2) DEFAULT 0,
  total_pending DECIMAL(12,2) DEFAULT 0,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Create COLLECTIONS table
CREATE TABLE collections (
  id TEXT PRIMARY KEY, -- We use custom IDs like REC-XXXX
  devotee_id TEXT REFERENCES devotees(id) ON DELETE CASCADE,
  date DATE DEFAULT CURRENT_DATE,
  year TEXT,
  type TEXT,
  book TEXT,
  leaf TEXT,
  paid DECIMAL(12,2) DEFAULT 0,
  unpaid DECIMAL(12,2) DEFAULT 0,
  remark TEXT,
  is_nirapara BOOLEAN DEFAULT FALSE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Create EXPENSE_CATEGORIES table
CREATE TABLE expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 5. Create EXPENSES table
CREATE TABLE expenses (
  id TEXT PRIMARY KEY,
  amount DECIMAL(12,2) NOT NULL,
  category TEXT REFERENCES expense_categories(name) ON UPDATE CASCADE,
  description TEXT,
  ref_bill TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE devotees ENABLE ROW LEVEL SECURITY;
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_categories ENABLE ROW LEVEL SECURITY;

-- 7. Create Policies (Allow authenticated users full access)
CREATE POLICY "Allow authenticated users full access on profiles" ON profiles FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access on devotees" ON devotees FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access on collections" ON collections FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access on expenses" ON expenses FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow authenticated users full access on expense_categories" ON expense_categories FOR ALL TO authenticated USING (true);

-- 8. Seed default categories
INSERT INTO expense_categories (name) VALUES 
('Maintenance'), 
('Electricity'), 
('Salary'), 
('Pooja Items'), 
('Other')
ON CONFLICT (name) DO NOTHING;
