import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        dashboard: "Dashboard",
        devotees: "Devotees",
        collections: "Collections",
        expenses: "Expenses",
        settings: "Settings",
        logout: "Logout",
        total_devotees: "Total Devotees",
        today_collection: "Today's Collection",
        total_collected: "Total Collected",
        total_pending: "Total Pending",
        total_expected: "Total Expected",
        recent_collections: "Recent Collections",
        quick_actions: "Quick Actions",
        add_devotee: "Add Devotee",
        log_payment: "Log Payment",
        add_expense: "Add Expense",
        search: "Search...",
        all_status: "All Status",
        paid: "Paid",
        pending: "Pending",
        address: "Address",
        phone: "Phone",
        name: "Name",
        welcome_title: "Jai Mahadeva!",
        welcome_subtitle: "Welcome back to Temple Management Portal",
        // Collections
        collections_history: "Collections History",
        date: "Date",
        receipt_id: "Receipt ID",
        transaction_id: "Transaction ID",
        devotee: "Devotee",
        event_details: "Event Details",
        amount: "Amount",
        all_time: "All Time",
        today: "Today",
        this_week: "This Week",
        this_month: "This Month",
        // Expenses
        expenses_mgmt: "Expenses Management",
        monthly_exp: "Monthly Expenditure",
        category: "Category",
        description: "Description",
        ref_bill: "Ref / Bill No",
        // Settings
        data_mgmt: "Data Management",
        data_portability: "Data Portability",
        backup_data: "Backup Data",
        restore_backup: "Restore Backup",
        sys_maintenance: "System Maintenance",
        restore_sample: "Restore Sample Data",
        purge_data: "Purge Everything",
        lang_pref: "Regional Preferences",
        // Parity Labels
        expected_amt: "Expected Amount",
        paid_amt: "Paid Amount",
        pending_amt: "Pending Amount",
        total_expenses: "Total Expenses",
        nirapara: "Nirapara",
        expense_id: "ID",
        payee_name: "Payee / Name",
        manage_categories: "Manage Categories",
        new_category: "New Category",
        pending_payments: "Pending Payments",
        quick_tip: "Quick Tip",
        quick_tip_body: "Use the Floating Action Button in the bottom corner to add devotees or log payments instantly from any screen.",
        view_devotees: "View Devotees",
        // Forms & Buttons
        update_records: "Update Records",
        register_devotee: "Register Devotee",
        confirm_payment: "Confirm Payment",
        save_expense: "Save Expense Record",
        name_required: "Name is required",
        phone_required: "Phone number is required",
        invalid_phone: "Enter a valid phone number",
        amount_required: "Amount must be greater than 0",
        select_devotee: "Select Devotee",
        payment_method: "Payment Method",
        purpose_note: "Purpose / Note",
        // Themes
        dark_mode: "Dark Mode",
        light_mode: "Light Mode",
        // New UI Keys
        temple_name: "Sree Mahadeva Temple",
        official_copy: "Official Copy",
        digital_record: "Digital Record",
        devotee_details: "Devotee Details",
        reg_reference: "Registry Reference",
        total_paid_label: "Total Paid",
        net_balance: "Net Balance",
        login_title: "Temple CRM",
        divine_portal: "Divine Management Portal",
        username: "Username",
        password: "Password",
        enter_portal: "Enter Portal",
        verifying: "Verifying...",
        chief_admin: "Chief Administrator",
        editor_role: "Editor",
        no_records_found: "No matching records found",
        search_placeholder: "Search by name, ID, phone or address...",
        navigation: "Navigation",
        quick_action_portal: "Quick Action Portal",
        dangerous_actions: "Dangerous Actions",
        purge_title: "Purge Entire Database",
        purge_warning: "DANGER: This will permanently delete ALL devotee records and expense history.",
        purge_confirm: "Yes, Purge Everything",
        restore_backup_confirm: "Yes, Restore Backup",
        sample_restore_title: "Restore Sample Data",
        sample_restore_msg: "This will reset your database with fresh demo records.",
        confirm_action: "Confirm Action",
        cancel: "Cancel",
        select: "Select",
        navigate: "Navigate",
        search_devotees: "Search Devotees",
        disable_privacy: "Disable Privacy Mode",
        enable_privacy: "Enable Privacy Mode",
        cash_flow_desc: "Monthly cash flow comparison",
        donation_range_desc: "Donation range distribution",
        growth_tip_body: "Your temple's financial ecosystem is growing. Maintain regular data entry to get even more precise predictions and historical audits.",
        computer_generated: "Computer generated – Signature not required",
        verified_by: "Verified by Temple Administration",
        contribution_details: "Contribution Summary",
        invalid_login: "Invalid username or password",
        settings_subtitle: "Manage your portal preferences and data",
        backup_json: "Backup JSON",
        backup_json_desc: "Full database backup",
        export_excel_desc: "Download .xlsx file",
        restore_json_desc: "Import .json file",
        import_excel_desc: "Upload .xlsx / .xls",
        excel_expected_cols: "Excel Import — Expected Columns",
        excel_import_hint: "💡 \"Mobile\", \"Full Name\", \"Phone No\" etc. are also accepted automatically.",
        change_password: "Change Password",
        master_only: "Master Admin Only",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",
        update_password: "Update Password",
        dangerous_actions_desc: "Database Maintenance",
        all_samples: "All Samples",
        pooram_samples: "Pooram Samples",
        vilakku_samples: "Vilakku Samples",
        purge_everything: "Purge Everything",
        last_update: "Last Update",
        privacy_vault_desc: "This portal uses local-first architecture for maximum privacy. All devotee information stays strictly in your browser's secure vault.",
        purge_confirm_btn: "Yes, Purge Everything",
        restore_samples_btn: "Yes, Restore Samples",
        restore_backup_btn: "Yes, Restore Backup",
        purge_db_title: "Purge Entire Database",
        purge_db_msg: "DANGER: This will permanently delete ALL devotee records and expense history. This cannot be undone.",
        restore_samples_title: "Restore Sample Data",
        restore_samples_msg: "This will reset your database with 1,000 fresh demo records for testing.",
        restore_backup_title: "Restore Backup",
        restore_backup_msg: "Are you sure you want to restore this backup? Your current database will be completely replaced.",
        all_clear: "All clear",
        pending_small: "pending",
        this_month_small: "This Month",
        export_csv: "Export CSV",
        id_label: "ID",
        actions: "Actions",
        record_deleted: "record deleted",
        showing: "Showing",
        of: "of",
        records_small: "records",
        previous: "Previous",
        next: "Next",
        edit_details: "Edit Devotee Details",
        confirm_del: "Confirm Deletion",
        no_devotees_yet: "No devotees yet",
        get_started_desc: "Get started by importing your data or loading demo records.",
        adjust_filters: "Try adjusting your search or filters.",
        clear_search: "Clear Search",
        del_confirm_msg: "Are you sure you want to delete",
        del_cannot_undo: "This action cannot be undone.",
        delete_record: "Delete Record",
        expected_amt_label: "Expected (₹)",
        record_updated: "Record updated successfully",
        record_created: "Record created successfully",
        full_name_placeholder: "Full Name",
        phone_placeholder: "Phone Number",
        address_placeholder: "Residential Address",
        collections_subtitle: "Recent payment records and spiritual contributions",
        col_search_placeholder: "Search by name, ID or type...",
        filtered_by: "Filtered by",
        no_transactions: "No transactions found matching your criteria",
        record_not_found: "Devotee record not found",
        back_to_directory: "Back to Directory",
        whatsapp_reminder: "WhatsApp Reminder",
        whatsapp_msg: "Namaste {name}, this is a gentle reminder from {temple}. Your pending contribution is ₹{amount}. Kindly settle at your earliest convenience. Thank you 🙏",
        expectation: "Expectation",
        collection: "Collection",
        collection_rate: "Collection Rate",
        pooram_tracker_title: "1. Pooram Tracker",
        vilakku_tracker_title: "2. Ayyappan Vilakku Tracker",
        log_pooram: "Log Pooram Entry",
        log_vilakku: "Log Vilakku Entry",
        year: "Year",
        book_no: "Book No",
        leaf_no: "Leaf No",
        remark: "Remark",
        no_records_tracker: "No records found in this tracker.",
        add_receipt: "Add Receipt",
        event_type: "Event Type",
        pooram_option: "Pooram Tracker",
        vilakku_option: "Ayyappan Vilakku",
        general_option: "General Collection",
        paid_amt_label: "Amount Paid (₹)",
        balance_label: "Balance / Unpaid (₹)",
        auto_calc_hint: "Auto-calculated from pending balance",
        remark_placeholder: "e.g. Paid for annual pooram",
        amt_gt_zero: "Amount must be greater than 0",
        date_required: "Date is required",
        save_event: "Save Event Record",
        update_event: "Update Event Record",
        payment_recorded: "Payment recorded successfully",
        collection_trend: "Collection Trend",
        from_last_month: "from last month",
        revenue_analysis: "Monthly revenue analysis",
        status_distribution: "Status Distribution",
        fulfillment_ratio: "Payment fulfillment ratio",
        urgent_collections: "Urgent Collections",
        view_all_pending: "View All Pending",
        no_transactions_yet: "No transactions recorded yet.",
        view_all_records: "View All Records",
        devotee_name: "Devotee Name",
        payment_recorded_for: "Payment Recorded For",
        no_pending_amount: "No pending amount — all paid!",
        donation: "Donation",
        monthly_contribution: "Monthly Contribution",
        cash: "Cash",
        cheque: "Cheque",
        online_transfer: "Online Transfer",
        other: "Other",
        purpose_placeholder: "e.g. Pooram contribution",
        recent_activity: "Recent Activity",
        last_system_events: "Last system events",
        payment_received: "Payment Received",
        new_devotee_added_msg: "New Devotee Added",
        added_to_db: "added to database",
        today_small: "Today",
        no_recent_events: "No recent events recorded.",
        rec_from: "from",
        top_pending_desc: "Top contributors with balances",
        all_payments_cleared: "All payments cleared!",
        export_excel: "Export Excel",
        import_excel: "Import Excel",
        backup_success: "Backup downloaded successfully",
        restore_success: "Backup restored successfully",
        purge_success: "Database purged successfully",
        excel_export_success: "Excel exported successfully",
        csv_export_success: "CSV exported successfully",
        demo_gen_success: "demo records generated successfully",
        pooram_gen_title: "Generate Pooram Samples",
        pooram_gen_msg: "This will add 500 new records exclusively with Pooram tracker data.",
        pooram_gen_btn: "Yes, Generate Pooram",
        vilakku_gen_title: "Generate Vilakku Samples",
        vilakku_gen_msg: "This will add 500 new records exclusively with Ayyappan Vilakku tracker data.",
        vilakku_gen_btn: "Yes, Generate Vilakku",
        pwd_changed: "Password changed successfully",
        pwd_updated: "Password updated successfully.",
        excel_import_preview: "Excel Import Preview",
        import_success_title: "Import Successful!",
        import_failed_title: "Import Failed",
        import_success_msg: "devotee records have been added to your database.",
        import_failed_hint: "Please check your Excel column headers match: Name, Phone, Address, Expected, Paid",
        done: "Done",
        close: "Close",
        required: "Required",
        min_chars: "Minimum 6 characters",
        pwd_mismatch: "Passwords do not match",
        enter_current_pwd: "Enter current password",
        enter_new_pwd: "Enter new password",
        repeat_new_pwd: "Repeat new password",
        regional_settings: "Regional Settings",
        standard_cat_error: "Standard categories cannot be deleted",
        yes: "Yes",
        delete_event_confirm: "Delete receipt #{id}?",
        delete_event_warn: "₹{amount} will be added back to pending. This cannot be undone.",
        total_label: "Total Amount",
        contribution_summary: "Contribution Summary",
        collection_type: "Collection Type",
        reg_id: "Registration ID",
        temple_dev_pooja: "Temple Development / Pooja",
        print_receipt: "Print Receipt",
        receipt_preview: "Receipt Preview",
        item: "Item",
        payee: "Payee",
        clear_filters: "Clear Filters"
    },
    ml: {
        dashboard: "ഡാഷ്ബോർഡ്",
        devotees: "ഭക്തർ",
        collections: "പിരിവ്",
        expenses: "ചെലവുകൾ",
        settings: "ക്രമീകരണങ്ങൾ",
        logout: "ലോഗൗട്ട്",
        total_devotees: "ആകെ ഭക്തർ",
        today_collection: "ഇന്നത്തെ പിരിവ്",
        total_collected: "പിരിച്ചെടുത്ത തുക",
        total_pending: "കുടിശ്ശിക",
        total_expected: "പ്രതീക്ഷിക്കുന്ന തുക",
        recent_collections: "സമീപകാല പിരിവുകൾ",
        quick_actions: "പെട്ടെന്നുള്ള പ്രവർത്തനങ്ങൾ",
        add_devotee: "ഭക്തനെ ചേർക്കുക",
        log_payment: "പണം രേഖപ്പെടുത്തുക",
        add_expense: "ചെലവ് ചേർക്കുക",
        search: "തിരയുക...",
        all_status: "എല്ലാ നിലയും",
        paid: "അടച്ചു",
        pending: "കുടിശ്ശിക",
        address: "വിലാസം",
        phone: "ഫോൺ",
        name: "പേര്",
        welcome_title: "ജയ് മഹാദേവ!",
        welcome_subtitle: "ക്ഷേത്ര പരിപാലന പോർട്ടലിലേക്ക് സ്വാഗതം",
        // Collections
        collections_history: "പിരിവ് ചരിത്രം",
        date: "തീയതി",
        receipt_id: "രസീത് ഐഡി",
        transaction_id: "ഇടപാട് ഐഡി",
        devotee: "ഭക്തൻ",
        event_details: "വിവരങ്ങൾ",
        amount: "തുക",
        all_time: "എല്ലാ കാലവും",
        today: "ഇന്ന്",
        this_week: "ഈ ആഴ്ച",
        this_month: "ഈ മാസം",
        // Expenses
        expenses_mgmt: "ചെലവ് മാനേജ്‌മെന്റ്",
        monthly_exp: "പ്രതിമാസ ചിലവ്",
        category: "വിഭാഗം",
        description: "വിവരണം",
        ref_bill: "റഫറൻസ് / ബില്ല് നം",
        // Settings
        data_mgmt: "ഡാറ്റാ കൈകാര്യം ചെയ്യൽ",
        data_portability: "ഡാറ്റാ കൈമാറ്റം",
        backup_data: "ബാക്കപ്പ് എടുക്കുക",
        restore_backup: "ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക",
        sys_maintenance: "സിസ്റ്റം മെയിന്റനൻസ്",
        restore_sample: "സാമ്പിൾ ഡാറ്റ വീണ്ടെടുക്കുക",
        purge_data: "എല്ലാം മായ്‌ക്കുക",
        lang_pref: "ഭാഷാ മുൻഗണനകൾ",
        // Parity Labels
        expected_amt: "പ്രതീക്ഷിക്കുന്ന തുക",
        paid_amt: "അടച്ച തുക",
        pending_amt: "കുടിശ്ശിക തുക",
        total_expenses: "ആകെ ചെലവുകൾ",
        nirapara: "നിറപറ",
        expense_id: "ഐഡി",
        payee_name: "പേര് / സ്വീകർത്താവ്",
        manage_categories: "വിഭാഗങ്ങൾ നിയന്ത്രിക്കുക",
        new_category: "പുതിയ വിഭാഗം",
        pending_payments: "കുടിശ്ശിക പേയ്‌മെന്റുകൾ",
        quick_tip: "ഒരു നുറുങ്ങ്",
        quick_tip_body: "ഏത് സ്ക്രീനിൽ നിന്നും ഭക്തരെ ചേർക്കാനോ പണം രേഖപ്പെടുത്താനോ താഴെ വലതുവശത്തുള്ള ബട്ടൺ ഉപയോഗിക്കുക.",
        view_devotees: "ഭക്തരെ കാണുക",
        // Forms & Buttons
        update_records: "വിവരങ്ങൾ പുതുക്കുക",
        register_devotee: "ഭക്തനെ ചേർക്കുക",
        confirm_payment: "പണം സ്ഥിരീകരിക്കുക",
        save_expense: "ചെലവ് രേഖപ്പെടുത്തുക",
        name_required: "പേര് ആവശ്യമാണ്",
        phone_required: "ഫോൺ നമ്പർ ആവശ്യമാണ്",
        invalid_phone: "ശരിയായ ഫോൺ നമ്പർ നൽകുക",
        amount_required: "തുക പൂജ്യത്തേക്കാൾ കൂടുതലായിരിക്കണം",
        select_devotee: "ഭക്തനെ തിരഞ്ഞെടുക്കുക",
        payment_method: "പണം നൽകിയ രീതി",
        purpose_note: "ലക്ഷ്യം / കുറിപ്പ്",
        // Themes
        dark_mode: "ഡാർക്ക് മോഡ്",
        light_mode: "ലൈറ്റ് മോഡ്",
        // New UI Keys
        temple_name: "ശ്രീ മഹാദേവ ക്ഷേത്രം",
        official_copy: "ഔദ്യോഗിക പകർപ്പ്",
        digital_record: "ഡിജിറ്റൽ റെക്കോർഡ്",
        devotee_details: "ഭക്തന്റെ വിവരങ്ങൾ",
        reg_reference: "രജിസ്ട്രി വിവരങ്ങൾ",
        total_paid_label: "ആകെ ലഭിച്ചത്",
        net_balance: "ബാക്കി തുക",
        login_title: "ടെമ്പിൾ CRM",
        divine_portal: "ക്ഷേത്ര പരിപാലന പോർട്ടൽ",
        username: "ഉപയോക്തൃനാമം",
        password: "പാസ്‌വേഡ്",
        enter_portal: "പ്രവേശിക്കുക",
        verifying: "പരിശോധിക്കുന്നു...",
        chief_admin: "ചീഫ് അഡ്മിനിസ്ട്രേറ്റർ",
        editor_role: "എഡിറ്റർ",
        no_records_found: "വിവരങ്ങൾ ഒന്നും കണ്ടെത്താൻ കഴിഞ്ഞില്ല.",
        search_placeholder: "പേര്, ഐഡി, ഫോൺ അല്ലെങ്കിൽ വിലാസം ഉപയോഗിച്ച് തിരയുക...",
        navigation: "നാവിഗേഷൻ",
        quick_action_portal: "ക്വിക്ക് ആക്ഷൻ പോർട്ടൽ",
        dangerous_actions: "മറ്റ് പ്രവർത്തനങ്ങൾ",
        purge_title: "ഡാറ്റ മുഴുവനായി മായ്ക്കുക",
        purge_warning: "ജാഗ്രത: ഇത് എല്ലാ ഭക്തരുടെ വിവരങ്ങളും ചെലവ് വിവരങ്ങളും ശാശ്വതമായി ഇല്ലാതാക്കും.",
        purge_confirm: "അതെ, എല്ലാം മായ്ക്കുക",
        restore_backup_confirm: "അതെ, ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക",
        sample_restore_title: "സാമ്പിൾ ഡാറ്റ പുനഃസ്ഥാപിക്കുക",
        sample_restore_msg: "ഇത് ഡാറ്റാബേസിനെ സാമ്പിൾ വിവരങ്ങൾ ഉപയോഗിച്ച് പുനഃക്രമീകരിക്കും.",
        confirm_action: "സ്ഥിരീകരിക്കുക",
        cancel: "റദ്ദാക്കുക",
        select: "തിരഞ്ഞെടുക്കുക",
        navigate: "സഞ്ചരിക്കുക",
        search_devotees: "ഭക്തരെ തിരയുക",
        disable_privacy: "പ്രൈവസി മോഡ് മാറ്റുക",
        enable_privacy: "പ്രൈവസി മോഡ് ഓൺ ചെയ്യുക",
        cash_flow_desc: "പ്രതിമാസ വരവ് ചിലവ് താരതമ്യം",
        donation_range_desc: "സംഭാവനകളുടെ വിഭജനം",
        growth_tip_body: "നിങ്ങളുടെ ക്ഷേത്രത്തിന്റെ സാമ്പത്തിക വ്യവസ്ഥ വളരുകയാണ്. കൃത്യമായ കണക്കുകൾക്കായി വിവരങ്ങൾ യഥാസമയം രേഖപ്പെടുത്തുക.",
        computer_generated: "കമ്പ്യൂട്ടർ നിർമ്മിത രസീത് — ഒപ്പ് ആവശ്യമില്ല",
        verified_by: "ക്ഷേത്ര ഭരണസമിതി സാക്ഷ്യപ്പെടുത്തിയത്",
        contribution_details: "സംഭാവനയുടെ വിവരങ്ങൾ",
        invalid_login: "തെറ്റായ ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ്",
        settings_subtitle: "പോർട്ടൽ ക്രമീകരണങ്ങളും ഡാറ്റയും കൈകാര്യം ചെയ്യുക",
        backup_json: "ബാക്കപ്പ് JSON",
        backup_json_desc: "മുഴുവൻ ഡാറ്റയും ബാക്കപ്പ് ചെയ്യുക",
        export_excel_desc: ".xlsx ഫയൽ ഡൗൺലോഡ് ചെയ്യുക",
        restore_json_desc: ".json ഫയൽ പുനഃസ്ഥാപിക്കുക",
        import_excel_desc: ".xlsx / .xls അപ്‌ലോഡ് ചെയ്യുക",
        excel_expected_cols: "എക്സൽ ഇംപോർട്ട് — വേണ്ട കോളം തലക്കെട്ടുകൾ",
        excel_import_hint: "💡 \"Mobile\", \"Full Name\", \"Phone No\" തുടങ്ങിയവയും സ്വീകരിക്കും.",
        change_password: "പാസ്‌വേഡ് മാറ്റുക",
        master_only: "മാസ്റ്റർ അഡ്മിന് മാത്രം",
        current_password: "നിലവിലെ പാസ്‌വേഡ്",
        new_password: "പുതിയ പാസ്‌വേഡ്",
        confirm_new_password: "പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
        update_password: "പാസ്‌വേഡ് പുതുക്കുക",
        dangerous_actions_desc: "ഡാറ്റാബേസ് മെയിന്റനൻസ്",
        all_samples: "എല്ലാ സാമ്പിളുകളും",
        pooram_samples: "പൂരം സാമ്പിളുകൾ",
        vilakku_samples: "വിളക്ക് സാമ്പിളുകൾ",
        purge_everything: "എല്ലാം മായ്ക്കുക",
        last_update: "അവസാനം പുതുക്കിയത്",
        privacy_vault_desc: "ഈ പോർട്ടൽ നിങ്ങളുടെ സ്വകാര്യതയ്ക്ക് മുൻഗണന നൽകുന്നു. എല്ലാ വിവരങ്ങളും നിങ്ങളുടെ ബ്രൗസറിൽ സുരക്ഷിതമായിരിക്കും.",
        purge_confirm_btn: "അതെ, എല്ലാം മായ്ക്കുക",
        restore_samples_btn: "അതെ, സാമ്പിളുകൾ പുനഃസ്ഥാപിക്കുക",
        restore_backup_btn: "അതെ, ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക",
        purge_db_title: "ഡാറ്റാബേസ് മായ്ക്കുക",
        purge_db_msg: "ജാഗ്രത: ഇത് എല്ലാ ഭക്തരുടെ വിവരങ്ങളും ചെലവ് വിവരങ്ങളും ശാശ്വതമായി ഇല്ലാതാക്കും. ഇത് മാറ്റാൻ കഴിയില്ല.",
        restore_samples_title: "സാമ്പിൾ ഡാറ്റ പുനഃസ്ഥാപിക്കുക",
        restore_samples_msg: "ഇത് 1000 പുതിയ സാമ്പിൾ വിവരങ്ങൾ ഉപയോഗിച്ച് ഡാറ്റാബേസിനെ പുനഃക്രമീകരിക്കും.",
        restore_backup_title: "ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുക",
        restore_backup_msg: "നിങ്ങൾക്ക് ഈ ബാക്കപ്പ് പുനഃസ്ഥാപിക്കണമെന്ന് ഉറപ്പാണോ? നിങ്ങളുടെ നിലവിലെ വിവരങ്ങൾ പൂർണ്ണമായും മാറ്റപ്പെടും.",
        all_clear: "കുടിശ്ശിക ഒന്നുമില്ല!",
        pending_small: "കുടിശ്ശിക",
        this_month_small: "ഈ മാസം",
        export_csv: "CSV എക്സ്പോർട്ട്",
        id_label: "ഐഡി",
        actions: "പ്രവർത്തനങ്ങൾ",
        record_deleted: "വിവരം നീക്കം ചെയ്തു",
        showing: "കാണിക്കുന്നത്",
        of: "ആകെ",
        records_small: "വിവരങ്ങൾ",
        previous: "പിന്നിലേക്ക്",
        next: "മുന്നോട്ട്",
        edit_details: "വിവരങ്ങൾ പുതുക്കുക",
        confirm_del: "ഡിലീറ്റ് സ്ഥിരീകരിക്കുക",
        no_devotees_yet: "ഭക്തരുടെ വിവരങ്ങൾ ലഭ്യമല്ല",
        get_started_desc: "ഡാറ്റ ഇമ്പോർട്ട് ചെയ്തോ ഡെമോ വിവരങ്ങൾ ഉപയോഗിച്ചോ തുടങ്ങുക.",
        adjust_filters: "സെർച്ച് അല്ലെങ്കിൽ ഫിൽട്ടറുകൾ മാറ്റി നോക്കുക.",
        clear_search: "സെർച്ച് ക്ലിയർ ചെയ്യുക",
        del_confirm_msg: "നിങ്ങൾക്ക് ഇത് നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ",
        del_cannot_undo: "ഈ പ്രവർത്തനം മാറ്റാൻ കഴിയില്ല.",
        delete_record: "ഡിലീറ്റ് ചെയ്യുക",
        expected_amt_label: "പ്രതീക്ഷിക്കുന്ന തുക (₹)",
        record_updated: "വിവരങ്ങൾ വിജയകരമായി പുതുക്കി",
        record_created: "വിവരങ്ങൾ വിജയകരമായി ചേർത്തു",
        full_name_placeholder: "പൂർണ്ണരൂപത്തിലുള്ള പേര്",
        phone_placeholder: "ഫോൺ നമ്പർ",
        address_placeholder: "താമസസ്ഥലം",
        collections_subtitle: "സമീപകാല പേയ്‌മെന്റ് റെക്കോർഡുകളും ആത്മീയ സംഭാവനകളും",
        col_search_placeholder: "പേര്, ഐഡി അല്ലെങ്കിൽ തരം ഉപയോഗിച്ച് തിരയുക...",
        filtered_by: "ഫിൽട്ടർ ചെയ്തത്",
        no_transactions: "വിവരങ്ങൾ ഒന്നും കണ്ടെത്താൻ കഴിഞ്ഞില്ല.",
        record_not_found: "വിവരങ്ങൾ ലഭ്യമായില്ല",
        back_to_directory: "ഡയറക്ടറിയിലേക്ക് മടങ്ങുക",
        whatsapp_reminder: "വാട്സാപ്പ് സന്ദേശം",
        whatsapp_msg: "നമസ്കാരം {name}, {temple}-ൽ നിന്നും ഒരു ഓർമ്മപ്പെടുത്തൽ. നിങ്ങളുടെ കുടിശ്ശിക തുക: ₹{amount}. ദയവായി ഇത് അടയ്ക്കാൻ ശ്രദ്ധിക്കുക. നന്ദി 🙏",
        expectation: "പ്രതീക്ഷിക്കുന്ന തുക",
        collection: "ലഭിച്ച തുക",
        collection_rate: "ശതമാനം",
        pooram_tracker_title: "1. പൂരം ട്രാക്കർ",
        vilakku_tracker_title: "2. അയ്യപ്പൻ വിളക്ക് ട്രാക്കർ",
        log_pooram: "പൂരം വിവരം ചേർക്കുക",
        log_vilakku: "വിളക്ക് വിവരം ചേർക്കുക",
        year: "വർഷം",
        book_no: "ബുക്ക് നമ്പർ",
        leaf_no: "പേജ് നമ്പർ",
        remark: "മറ്റു വിവരങ്ങൾ",
        no_records_tracker: " വിവരങ്ങൾ ലഭ്യമായില്ല.",
        add_receipt: "രസീത് ചേർക്കുക",
        event_type: "ഇനം",
        pooram_option: "പൂരം ട്രാക്കർ",
        vilakku_option: "അയ്യപ്പൻ വിളക്ക്",
        general_option: "ജനറൽ കളക്ഷൻ",
        paid_amt_label: "അടച്ച തുക (₹)",
        balance_label: "ബാക്കി തുക (₹)",
        auto_calc_hint: "ബാക്കി തുക തനിയെ കണക്കാക്കും",
        remark_placeholder: "മറ്റു കുറിപ്പുകൾ ഇവിടെ ചേർക്കാം",
        amt_gt_zero: "തുക 0-ൽ കൂടുതൽ ആയിരിക്കണം",
        date_required: "തിയതി നിർബന്ധമാണ്",
        save_event: "സേവ് ചെയ്യുക",
        update_event: "പുതുക്കുക",
        payment_recorded: "പേയ്‌മെന്റ് രേഖപ്പെടുത്തി",
        collection_trend: "വരവ് വിവരങ്ങൾ",
        from_last_month: "കഴിഞ്ഞ മാസത്തേക്കാൾ",
        revenue_analysis: "പ്രതിമാസ വരവ് വിവരങ്ങൾ",
        status_distribution: "നിലവിലെ അവസ്ഥ",
        fulfillment_ratio: "പേയ്‌മെന്റ് അനുപാതം",
        urgent_collections: "പിരിഞ്ഞു കിട്ടാനുള്ളവ",
        view_all_pending: "മുഴുവൻ കുടിശ്ശികയും കാണുക",
        no_transactions_yet: "ഇടപാടുകൾ ഒന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.",
        view_all_records: "മുഴുവൻ ചരിത്രവും കാണുക",
        devotee_name: "ഭക്തന്റെ പേര്",
        payment_recorded_for: "തുക രേഖപ്പെടുത്തി",
        no_pending_amount: "കുടിശ്ശിക ഒന്നുമില്ല — എല്ലാം അടച്ചു!",
        donation: "സംഭാവന",
        monthly_contribution: "മാസവരി",
        cash: "പണമായി",
        cheque: "ചെക്ക്",
        online_transfer: "ഓൺലൈൻ ട്രാൻസ്ഫർ",
        other: "മറ്റുള്ളവ",
        purpose_placeholder: "ഉദാഹരണത്തിന്: പൂരം സംഭാവന",
        recent_activity: "സമീപകാല പ്രവർത്തനങ്ങൾ",
        last_system_events: "സിസ്റ്റം പ്രവർത്തനങ്ങൾ",
        payment_received: "പേയ്‌മെന്റ് ലഭിച്ചു",
        new_devotee_added_msg: "പുതിയ ആളെ ചേർത്തു",
        added_to_db: "ഡാറ്റാബേസിൽ ചേർത്തു",
        today_small: "ഇന്ന്",
        no_recent_events: "പ്രവർത്തനങ്ങൾ ഒന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.",
        rec_from: "നിന്നും",
        top_pending_desc: "പിരിഞ്ഞു കിട്ടാനുള്ള പ്രധാന ആളുകൾ",
        all_payments_cleared: "കുടിശ്ശിക ഒന്നുമില്ല!",
        export_excel: "Excel എക്സ്പോർട്ട്",
        import_excel: "Excel ഇമ്പോർട്ട്",
        backup_success: "ബാക്കപ്പ് ഡൗൺലോഡ് ചെയ്തു",
        restore_success: "ബാക്കപ്പ് പുനഃസ്ഥാപിച്ചു",
        purge_success: "ഡാറ്റാബേസ് പൂർണ്ണമായും മായ്ച്ചു",
        excel_export_success: "Excel എക്സ്പോർട്ട് വിജയിച്ചു",
        csv_export_success: "CSV എക്സ്പോർട്ട് വിജയിച്ചു",
        demo_gen_success: "സാമ്പിൾ വിവരങ്ങൾ തയ്യാറായി",
        pooram_gen_title: "പൂരം സാമ്പിളുകൾ",
        pooram_gen_msg: "ഇത് 500 പുതിയ പൂരം സാമ്പിൾ വിവരങ്ങൾ ചേർക്കും.",
        pooram_gen_btn: "അതെ, പൂരം സാമ്പിളുകൾ ചേർക്കുക",
        vilakku_gen_title: "വിളക്ക് സാമ്പിളുകൾ",
        vilakku_gen_msg: "ഇത് 500 പുതിയ വിളക്ക് സാമ്പിൾ വിവരങ്ങൾ ചേർക്കും.",
        vilakku_gen_btn: "അതെ, വിളക്ക് സാമ്പിളുകൾ ചേർക്കുക",
        pwd_changed: "പാസ്‌വേഡ് വിജയകരമായി മാറ്റി",
        pwd_updated: "പാസ്‌വേഡ് പുതുക്കി കഴിഞ്ഞു.",
        excel_import_preview: "Excel ഇമ്പോർട്ട് പ്രിവ്യൂ",
        import_success_title: "വിജയകരമായി ചേർത്തു!",
        import_failed_title: "ചേർക്കാൻ കഴിഞ്ഞില്ല",
        import_success_msg: "ഭക്തരുടെ വിവരങ്ങൾ ഡാറ്റാബേസിൽ ചേർത്തു.",
        import_failed_hint: "ദയവായി Excel കോളം തലക്കെട്ടുകൾ പരിശോധിക്കുക: Name, Phone, Address, Expected, Paid",
        done: "ശരി",
        close: "അടയ്ക്കുക",
        required: "ആവശ്യമാണ്",
        min_chars: "കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ വേണം",
        pwd_mismatch: "പാസ്‌വേഡുകൾ തമ്മിൽ ചേരുന്നില്ല",
        enter_current_pwd: "നിലവിലെ പാസ്‌വേഡ് നൽകുക",
        enter_new_pwd: "പുതിയ പാസ്‌വേഡ് നൽകുക",
        repeat_new_pwd: "പുതിയ പാസ്‌വേഡ് ആവർത്തിക്കുക",
        regional_settings: "പ്രാദേശിക ക്രമീകരണങ്ങൾ",
        standard_cat_error: "സ്ഥിരമായ വിഭാഗങ്ങൾ മാറ്റാൻ കഴിയില്ല",
        yes: "അതെ",
        no: "ഇല്ല",
        delete_event_confirm: "രസീത് #{id} ഒഴിവാക്കണോ?",
        delete_event_warn: "₹{amount} കുടിശ്ശികയിലേക്ക് തിരികെ ചേർക്കപ്പെടും. ഇത് മാറ്റാൻ കഴിയില്ല.",
        total_label: "ആകെ തുക",
        contribution_summary: "സംഭാവന വിവരങ്ങൾ",
        collection_type: "പിരിവ് വിഭാഗം",
        reg_id: "രജിസ്ട്രേഷൻ ഐഡി",
        temple_dev_pooja: "ക്ഷേമ വികസനം / പൂജ",
        print_receipt: "രസീത് പ്രിന്റ് ചെയ്യുക",
        receipt_preview: "രസീത് പരിശോധന",
        item: "വിഭാഗം",
        payee: "പണം നൽകിയത്",
        clear_filters: "ഫിൽട്ടറുകൾ ഒഴിവാക്കുക"
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => localStorage.getItem('temple_crm_lang') || 'en');

    useEffect(() => {
        localStorage.setItem('temple_crm_lang', language);
    }, [language]);

    const t = translations[language];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
